name: act
version: 0.0.1
description: A sample command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  watcher: 'any'
  diff_match_patch: ">=0.2.1 <0.3.0"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
